spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/webdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework: info
    org.zerock: debug
    org.springframework.security: debug

org:
  zerock:
    jwt:
      secret: hello1234567890
